# Generated by Django 4.2.2 on 2023-12-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_testfooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfooditem',
            name='callories',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
