# Generated by Django 5.1.1 on 2024-10-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('meal', models.TextField(null=True)),
                ('station', models.TextField(null=True)),
                ('dining_hall', models.TextField(null=True)),
            ],
        ),
    ]
