# Generated by Django 4.2.2 on 2023-06-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
