# Generated by Django 4.2.2 on 2023-08-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0002_delete_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=1024, verbose_name='question 1')),
                ('question2', models.CharField(max_length=1024, verbose_name='question 2')),
                ('question3', models.CharField(max_length=1024, verbose_name='question 3')),
                ('question4', models.CharField(max_length=1024, verbose_name='question 4')),
                ('question5', models.CharField(max_length=1024, verbose_name='question 5')),
            ],
        ),
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('title', models.CharField(max_length=256, verbose_name='Topic')),
                ('description', models.TextField(blank=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.survey')),
            ],
        ),
    ]
