# Generated by Django 4.2.5 on 2023-10-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barh.station'),
        ),
    ]
