# Generated by Django 4.2.2 on 2023-12-05 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blitman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='rating',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blitman.station'),
        ),
    ]
