# Generated by Django 4.2.2 on 2023-10-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratedfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedfooditem',
            name='dining_hall',
            field=models.CharField(default='commons', max_length=50),
        ),
    ]
