# Generated by Django 4.2.2 on 2023-11-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratedfood', '0002_ratedfooditem_gluten_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedfooditem',
            name='meal_time',
            field=models.CharField(default='breakfast', max_length=50),
        ),
    ]
